# Generated by Django 4.1.7 on 2023-11-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='theblog/media/images/uploads/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_tag', models.CharField(blank=True, max_length=255)),
                ('image_description', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_tag', models.CharField(blank=True, max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
