# Generated by Django 4.1.7 on 2023-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(default='bori_blog', max_length=255),
        ),
    ]
