# Generated by Django 4.1.7 on 2023-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(blank=True, default='bori_blog', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(blank=True, default="Bori's Blog", max_length=255),
        ),
    ]
