# Generated by Django 4.1.7 on 2023-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_alter_post_meta_tag_alter_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
