# Generated by Django 4.1.7 on 2023-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_post_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default="Bori's Blog", max_length=255),
        ),
    ]
