# Generated by Django 4.1.7 on 2023-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_alter_post_header_image_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
