# Generated by Django 4.1.7 on 2023-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_alter_post_header_image_alter_post_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='theblog/media/images/uploads/'),
        ),
    ]
